/**
 * RailOpt - Realistic Indian Railways Mock Dataset
 * Strictly conforming to schemas in types.js
 */

export const mockMaintenanceJobs = [
    {
        id: "JOB-ENG-101",
        title: "Mechanized Track Tamping & Alignment (CSM 09-32)",
        department: "ENG",
        departmentName: "Civil Engineering (Permanent Way)",
        section: "FDB-PWL",
        trackLine: "FDB-PWL_UP",
        durationMinutes: 210,
        priority: 5,
        urgency: "CRITICAL",
        requiresPowerBlock: false,
        requiresTrafficBlock: true,
        requiresSpeedRestriction: true,
        speedRestrictionKmh: 30,
        requiredResource: "CSM 09-32 Continuous Action Tamping Machine",
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 90,
        latestEndMinute: 360,
        description: "Deep tamping of KM 42/1 to 48/5 on UP Main line to eliminate severe gauge variations detected by OMS car."
    },
    {
        id: "JOB-TRD-201",
        title: "Annual OHE Cantilever & Contact Wire Overhaul",
        department: "TRD",
        departmentName: "Traction Distribution (OHE)",
        section: "FDB-PWL",
        trackLine: "FDB-PWL_UP",
        durationMinutes: 180,
        priority: 4,
        urgency: "HIGH",
        requiresPowerBlock: true,
        requiresTrafficBlock: true,
        requiresSpeedRestriction: false,
        requiredResource: "8-Wheeler Self-Propelled OHE Tower Wagon",
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 90,
        latestEndMinute: 360,
        description: "Re-tensioning contact wire and replacement of defective composite insulators between Mast 44/12 and 46/20."
    },
    {
        id: "JOB-ST-301",
        title: "Electronic Interlocking Point Machine 104A/B Overhaul",
        department: "S_T",
        departmentName: "Signaling & Telecommunication",
        section: "TKD-FDB",
        trackLine: "TKD-FDB_DN",
        durationMinutes: 120,
        priority: 4,
        urgency: "HIGH",
        requiresPowerBlock: false,
        requiresTrafficBlock: true,
        requiresSpeedRestriction: true,
        speedRestrictionKmh: 45,
        requiredResource: "Electronic Interlocking Mobile Testing Unit",
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 80,
        latestEndMinute: 300,
        description: "Replacement of drive motor and ground connections on crossover point 104A/B at Tuglakabad South cabin."
    },
    {
        id: "JOB-ENG-102",
        title: "Ballast Cleaning & Dynamic Track Stabilization",
        department: "ENG",
        departmentName: "Civil Engineering (Permanent Way)",
        section: "PWL-KDS",
        trackLine: "PWL-KDS_DN",
        durationMinutes: 240,
        priority: 4,
        urgency: "HIGH",
        requiresPowerBlock: false,
        requiresTrafficBlock: true,
        requiresSpeedRestriction: true,
        speedRestrictionKmh: 30,
        requiredResource: "Dynamic Track Stabilizer (DTS-102)",
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 100,
        latestEndMinute: 360,
        description: "Deep ballast screening on KM 78/4 to 81/2 DN line followed by dynamic compaction to restore track elasticity."
    },
    {
        id: "JOB-TRD-202",
        title: "Isolator Switch & Neutral Section Inspection",
        department: "TRD",
        departmentName: "Traction Distribution (OHE)",
        section: "PWL-KDS",
        trackLine: "PWL-KDS_DN",
        durationMinutes: 150,
        priority: 3,
        urgency: "MEDIUM",
        requiresPowerBlock: true,
        requiresTrafficBlock: true,
        requiresSpeedRestriction: false,
        requiredResource: "OHE Inspection Ladder Gang",
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 100,
        latestEndMinute: 360,
        description: "Preventive thermo-vision thermography defect rectification on Section Isolator SI-82/1."
    },
    {
        id: "JOB-ST-302",
        title: "High-Speed Multi-Section Digital Axle Counter (MSDAC) Tuning",
        department: "S_T",
        departmentName: "Signaling & Telecommunication",
        section: "FDB-PWL",
        trackLine: "FDB-PWL_UP",
        durationMinutes: 90,
        priority: 3,
        urgency: "MEDIUM",
        requiresPowerBlock: false,
        requiresTrafficBlock: true,
        requiresSpeedRestriction: false,
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 90,
        latestEndMinute: 360,
        description: "Quarterly calibration and tuning of track-mounted wheel detection sensor heads on UP high-speed line."
    },
    {
        id: "JOB-ENG-103",
        title: "Ultrasonic Flaw Detection (USFD) Rail Testing",
        department: "ENG",
        departmentName: "Civil Engineering (Permanent Way)",
        section: "MTJ-AGC",
        trackLine: "MTJ-AGC_UP",
        durationMinutes: 150,
        priority: 3,
        urgency: "MEDIUM",
        requiresPowerBlock: false,
        requiresTrafficBlock: true,
        requiresSpeedRestriction: false,
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 120,
        latestEndMinute: 360,
        description: "Digital ultrasonic flaw detection on thermit welds and continuous welded rail segments."
    },
    {
        id: "JOB-ST-303",
        title: "Automatic Block Signal LED Retrofit & Tail Cable Check",
        department: "S_T",
        departmentName: "Signaling & Telecommunication",
        section: "NDLS-TKD",
        trackLine: "NDLS-TKD_UP",
        durationMinutes: 90,
        priority: 2,
        urgency: "ROUTINE",
        requiresPowerBlock: false,
        requiresTrafficBlock: false,
        requiresSpeedRestriction: false,
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 60,
        latestEndMinute: 360,
        description: "Routine replacement of red/yellow LED signal units on Auto Signals AS-12 and AS-14."
    },
    {
        id: "JOB-ENG-104",
        title: "Turnout Sleepers Replacement on 3rd Goods Line",
        department: "ENG",
        departmentName: "Civil Engineering (Permanent Way)",
        section: "FDB-PWL",
        trackLine: "FDB-PWL_3RD",
        durationMinutes: 120,
        priority: 3,
        urgency: "MEDIUM",
        requiresPowerBlock: false,
        requiresTrafficBlock: true,
        requiresSpeedRestriction: false,
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 720,
        latestEndMinute: 900,
        description: "Replacement of damaged concrete sleepers on goods loop turnout #208."
    },
    {
        id: "JOB-MECH-401",
        title: "Freight Yard Brake Rigging & Air Brake Testing Block",
        department: "MECH",
        departmentName: "Mechanical (Carriage & Wagon)",
        section: "TKD-FDB",
        trackLine: "TKD-FDB_3RD",
        durationMinutes: 120,
        priority: 2,
        urgency: "ROUTINE",
        requiresPowerBlock: false,
        requiresTrafficBlock: true,
        requiresSpeedRestriction: false,
        status: "SCHEDULED",
        requestedDate: "2026-09-01",
        earliestStartMinute: 600,
        latestEndMinute: 780,
        description: "Intensive rolling stock safety audit on container rake line 4."
    }
];

export const mockTrainMovements = [
    {
        trainNumber: "22436",
        trainName: "Vande Bharat Express",
        trainType: "VANDE_BHARAT",
        priorityWeight: 35,
        direction: "DN",
        origin: "NDLS",
        destination: "BSB",
        departureMinute: 360,
        arrivalMinute: 460,
        departureTimeStr: "06:00",
        arrivalTimeStr: "07:40",
        regulatedDelayMin: 0
    },
    {
        trainNumber: "12050",
        trainName: "Gatimaan Express",
        trainType: "VANDE_BHARAT",
        priorityWeight: 35,
        direction: "DN",
        origin: "NZM",
        destination: "AGC",
        departureMinute: 490,
        arrivalMinute: 590,
        departureTimeStr: "08:10",
        arrivalTimeStr: "09:50",
        regulatedDelayMin: 0
    },
    {
        trainNumber: "12952",
        trainName: "Mumbai Tejas Rajdhani",
        trainType: "RAJDHANI",
        priorityWeight: 35,
        direction: "DN",
        origin: "NDLS",
        destination: "MMCT",
        departureMinute: 1015,
        arrivalMinute: 1115,
        departureTimeStr: "16:55",
        arrivalTimeStr: "18:35",
        regulatedDelayMin: 0
    },
    {
        trainNumber: "12138",
        trainName: "Punjab Mail",
        trainType: "EXPRESS",
        priorityWeight: 15,
        direction: "DN",
        origin: "FZR",
        destination: "CSMT",
        departureMinute: 315,
        arrivalMinute: 435,
        departureTimeStr: "05:15",
        arrivalTimeStr: "07:15",
        regulatedDelayMin: 12
    },
    {
        trainNumber: "CONRAJ-01",
        trainName: "Container Cargo Special",
        trainType: "FREIGHT",
        priorityWeight: 5,
        direction: "DN",
        origin: "TKD",
        destination: "JNPT",
        departureMinute: 90,
        arrivalMinute: 210,
        departureTimeStr: "01:30",
        arrivalTimeStr: "03:30",
        regulatedDelayMin: 45
    },
    {
        trainNumber: "BTPN-04",
        trainName: "IOCL Petroleum Rake",
        trainType: "FREIGHT",
        priorityWeight: 5,
        direction: "UP",
        origin: "MTJ",
        destination: "TKD",
        departureMinute: 150,
        arrivalMinute: 270,
        departureTimeStr: "02:30",
        arrivalTimeStr: "04:30",
        regulatedDelayMin: 35
    }
];

export const mockBlockWindows = [
    {
        id: "WIN-FDB-PWL-NIGHT",
        section: "FDB-PWL",
        trackLine: "FDB-PWL_UP",
        startMinute: 90,
        endMinute: 330,
        startTimeStr: "01:30",
        endTimeStr: "05:30",
        windowType: "CORRIDOR",
        isActive: true,
        maxCapacityHours: 4.0
    },
    {
        id: "WIN-PWL-KDS-NIGHT",
        section: "PWL-KDS",
        trackLine: "PWL-KDS_DN",
        startMinute: 100,
        endMinute: 340,
        startTimeStr: "01:40",
        endTimeStr: "05:40",
        windowType: "CORRIDOR",
        isActive: true,
        maxCapacityHours: 4.0
    },
    {
        id: "WIN-TKD-FDB-NIGHT",
        section: "TKD-FDB",
        trackLine: "TKD-FDB_DN",
        startMinute: 80,
        endMinute: 300,
        startTimeStr: "01:20",
        endTimeStr: "05:00",
        windowType: "CORRIDOR",
        isActive: true,
        maxCapacityHours: 3.6
    },
    {
        id: "WIN-FDB-PWL-AFT",
        section: "FDB-PWL",
        trackLine: "FDB-PWL_3RD",
        startMinute: 720,
        endMinute: 870,
        startTimeStr: "12:00",
        endTimeStr: "14:30",
        windowType: "CORRIDOR",
        isActive: true,
        maxCapacityHours: 2.5
    }
];

export const mockConstraints = [
    {
        id: "RULE-SAFETY-01",
        name: "Disjunctive Track Occupancy Exclusivity",
        type: "HARD",
        category: "SAFETY",
        description: "Zero simultaneous non-shadow jobs or train movements on the identical track section.",
        isEnabled: true,
        penaltyOrBonusWeight: 10000,
        mathematicalFormulation: "interval(j1) ∩ interval(j2) = ∅ ∀ j1, j2 ∉ ShadowPair"
    },
    {
        id: "RULE-PWR-01",
        name: "Traction OHE Power Block Coupling",
        type: "HARD",
        category: "SAFETY",
        description: "Permanent way activities requiring OHE shutdown must be synchronized with TRD isolation permit.",
        isEnabled: true,
        penaltyOrBonusWeight: 5000,
        mathematicalFormulation: "requiresPowerBlock(j) ⇒ ∃ TRD_Block(start <= start(j), end >= end(j))"
    },
    {
        id: "RULE-MACH-01",
        name: "Heavy Machine (CSM/DTS/Tower Wagon) Exclusivity",
        type: "HARD",
        category: "RESOURCE",
        description: "A machine unit can only be allocated to one maintenance section at a time plus transit buffer.",
        isEnabled: true,
        penaltyOrBonusWeight: 8000,
        mathematicalFormulation: "NoOverlap([Interval(j) ∀ j requiring Machine_M])"
    },
    {
        id: "RULE-SHADOW-01",
        name: "Multi-Department Shadow Block Synergy Bonus",
        type: "SOFT",
        category: "SHADOW_SYNERGY",
        description: "Maximizes bundling of ENG + TRD + S&T blocks within identical track window.",
        isEnabled: true,
        penaltyOrBonusWeight: 4000,
        mathematicalFormulation: "Maximize ∑ (is_shadow(j1, j2) * 4000)"
    },
    {
        id: "RULE-TRAIN-01",
        name: "Vande Bharat & Rajdhani Punctuality Protection",
        type: "SOFT",
        category: "HEADWAY",
        description: "Strict penalty on passenger express regulation during maintenance block windows.",
        isEnabled: true,
        penaltyOrBonusWeight: 50,
        mathematicalFormulation: "Minimize ∑ (delay(t) * priority_weight(t))"
    }
];

export const mockOptimizedPlan = {
    runId: 101,
    timestamp: "2026-09-01 06:00:00",
    status: "OPTIMAL",
    totalJobsConsidered: 10,
    scheduledJobsCount: 10,
    unscheduledJobsCount: 0,
    totalMaintenanceHours: 25.5,
    totalTrainDelayMinutes: 92,
    blockUtilizationPct: 94.2,
    shadowBlockSynergyPct: 70.0,
    objectiveScore: 58240.0,
    solverTimeSeconds: 0.84,
    scheduledBlocks: [
        {
            blockId: "BLK-101-01",
            jobId: "JOB-ENG-101",
            title: "JOB-ENG-101 - ENG",
            department: "ENG",
            departmentColor: "#003366",
            section: "FDB-PWL",
            trackLine: "FDB-PWL_UP",
            startMinute: 90,
            endMinute: 300,
            startTimeStr: "01:30",
            endTimeStr: "05:00",
            durationMinutes: 210,
            isShadowBlock: true,
            pairedJobIds: ["JOB-TRD-201", "JOB-ST-302"],
            resourceAssigned: "CSM 09-32 Tamping Machine",
            affectedTrains: [
                { trainNumber: "CONRAJ-01", delayMin: 45, action: "Held at Tuglakabad Freight Yard" }
            ],
            decisionExplanation: "Scheduled during 01:30-05:00 night corridor window. Co-located as a Shadow Block with JOB-TRD-201 and JOB-ST-302, eliminating 2 independent track closures."
        },
        {
            blockId: "BLK-101-02",
            jobId: "JOB-TRD-201",
            title: "JOB-TRD-201 - TRD",
            department: "TRD",
            departmentColor: "#d97706",
            section: "FDB-PWL",
            trackLine: "FDB-PWL_UP",
            startMinute: 90,
            endMinute: 270,
            startTimeStr: "01:30",
            endTimeStr: "04:30",
            durationMinutes: 180,
            isShadowBlock: true,
            pairedJobIds: ["JOB-ENG-101", "JOB-ST-302"],
            resourceAssigned: "OHE Tower Wagon (TRD-01)",
            affectedTrains: [],
            decisionExplanation: "OHE power isolation bundled directly under the UP track traffic block granted for JOB-ENG-101."
        },
        {
            blockId: "BLK-101-03",
            jobId: "JOB-ST-302",
            title: "JOB-ST-302 - S_T",
            department: "S_T",
            departmentColor: "#0284c7",
            section: "FDB-PWL",
            trackLine: "FDB-PWL_UP",
            startMinute: 90,
            endMinute: 180,
            startTimeStr: "01:30",
            endTimeStr: "03:00",
            durationMinutes: 90,
            isShadowBlock: true,
            pairedJobIds: ["JOB-ENG-101", "JOB-TRD-201"],
            resourceAssigned: "S&T Fast Response Team",
            affectedTrains: [],
            decisionExplanation: "Axle counter calibration scheduled in shadow of heavy track tamping."
        },
        {
            blockId: "BLK-101-04",
            jobId: "JOB-ENG-102",
            title: "JOB-ENG-102 - ENG",
            department: "ENG",
            departmentColor: "#003366",
            section: "PWL-KDS",
            trackLine: "PWL-KDS_DN",
            startMinute: 100,
            endMinute: 340,
            startTimeStr: "01:40",
            endTimeStr: "05:40",
            durationMinutes: 240,
            isShadowBlock: true,
            pairedJobIds: ["JOB-TRD-202"],
            resourceAssigned: "Dynamic Track Stabilizer (DTS-102)",
            affectedTrains: [
                { trainNumber: "12138", delayMin: 12, action: "Regulated before Palwal" }
            ],
            decisionExplanation: "Deep screening block scheduled with OHE isolator maintenance on DN line."
        },
        {
            blockId: "BLK-101-05",
            jobId: "JOB-TRD-202",
            title: "JOB-TRD-202 - TRD",
            department: "TRD",
            departmentColor: "#d97706",
            section: "PWL-KDS",
            trackLine: "PWL-KDS_DN",
            startMinute: 100,
            endMinute: 250,
            startTimeStr: "01:40",
            endTimeStr: "04:10",
            durationMinutes: 150,
            isShadowBlock: true,
            pairedJobIds: ["JOB-ENG-102"],
            resourceAssigned: "Ladder Gang TRD-02",
            affectedTrains: [],
            decisionExplanation: "Isolator switch replacement completed under shadow of ballast cleaning."
        },
        {
            blockId: "BLK-101-06",
            jobId: "JOB-ST-301",
            title: "JOB-ST-301 - S_T",
            department: "S_T",
            departmentColor: "#0284c7",
            section: "TKD-FDB",
            trackLine: "TKD-FDB_DN",
            startMinute: 80,
            endMinute: 200,
            startTimeStr: "01:20",
            endTimeStr: "03:20",
            durationMinutes: 120,
            isShadowBlock: false,
            pairedJobIds: [],
            resourceAssigned: "Mobile S&T Diagnostic Unit",
            affectedTrains: [],
            decisionExplanation: "Point machine overhaul executed during Tuglakabad yard night traffic lull."
        },
        {
            blockId: "BLK-101-07",
            jobId: "JOB-ENG-103",
            title: "JOB-ENG-103 - ENG",
            department: "ENG",
            departmentColor: "#003366",
            section: "MTJ-AGC",
            trackLine: "MTJ-AGC_UP",
            startMinute: 120,
            endMinute: 270,
            startTimeStr: "02:00",
            endTimeStr: "04:30",
            durationMinutes: 150,
            isShadowBlock: false,
            pairedJobIds: [],
            resourceAssigned: "Digital USFD Cart",
            affectedTrains: [
                { trainNumber: "BTPN-04", delayMin: 35, action: "Held at Mathura Jn" }
            ],
            decisionExplanation: "Ultrasonic rail flaw testing granted on Mathura-Agra line."
        },
        {
            blockId: "BLK-101-08",
            jobId: "JOB-ST-303",
            title: "JOB-ST-303 - S_T",
            department: "S_T",
            departmentColor: "#0284c7",
            section: "NDLS-TKD",
            trackLine: "NDLS-TKD_UP",
            startMinute: 60,
            endMinute: 150,
            startTimeStr: "01:00",
            endTimeStr: "02:30",
            durationMinutes: 90,
            isShadowBlock: false,
            pairedJobIds: [],
            resourceAssigned: "Signal Maintenance Gang",
            affectedTrains: [],
            decisionExplanation: "Non-traffic-blocking signal LED retrofit completed."
        },
        {
            blockId: "BLK-101-09",
            jobId: "JOB-ENG-104",
            title: "JOB-ENG-104 - ENG",
            department: "ENG",
            departmentColor: "#003366",
            section: "FDB-PWL",
            trackLine: "FDB-PWL_3RD",
            startMinute: 720,
            endMinute: 840,
            startTimeStr: "12:00",
            endTimeStr: "14:00",
            durationMinutes: 120,
            isShadowBlock: false,
            pairedJobIds: [],
            resourceAssigned: "P-Way Section Gang",
            affectedTrains: [],
            decisionExplanation: "Goods line turnout sleeper renewal scheduled during afternoon lull."
        },
        {
            blockId: "BLK-101-10",
            jobId: "JOB-MECH-401",
            title: "JOB-MECH-401 - MECH",
            department: "MECH",
            departmentColor: "#4b5563",
            section: "TKD-FDB",
            trackLine: "TKD-FDB_3RD",
            startMinute: 600,
            endMinute: 720,
            startTimeStr: "10:00",
            endTimeStr: "12:00",
            durationMinutes: 120,
            isShadowBlock: false,
            pairedJobIds: [],
            resourceAssigned: "TXR Carriage & Wagon Team",
            affectedTrains: [],
            decisionExplanation: "Freight rolling stock examination block granted on 3rd siding."
        }
    ],
    unscheduledJobs: [],
    conflictsResolved: [
        {
            id: "CONF-01",
            conflictType: "TRACK_OCCUPANCY",
            severity: "RESOLVED",
            description: "Concurrent UP line requests from ENG (JOB-ENG-101), TRD (JOB-TRD-201), and S&T (JOB-ST-302) on Faridabad-Palwal.",
            resolutionApplied: "Synchronized into single 3.5-hour Shadow Block window (01:30 - 05:00) with zero collision."
        },
        {
            id: "CONF-02",
            conflictType: "TRAIN_HEADWAY",
            severity: "RESOLVED",
            description: "Potential path overlap between Freight CONRAJ-01 and night tamping block on UP line.",
            resolutionApplied: "Freight rake held at Tuglakabad yard loop; Vande Bharat #22436 preserved with 0 min delay."
        }
    ]
};

export const mockPlanChange = {
    scenarioName: "Emergency Fracture + Freight Surge Simulation",
    baselineRunId: 101,
    simulatedPlan: {
        ...mockOptimizedPlan,
        runId: 102,
        totalJobsConsidered: 11,
        scheduledJobsCount: 11,
        totalMaintenanceHours: 28.0,
        totalTrainDelayMinutes: 112,
        blockUtilizationPct: 96.8,
        shadowBlockSynergyPct: 72.7
    },
    deltaScheduledJobs: 1,
    deltaTrainDelayMinutes: 20,
    deltaUtilizationPct: 2.6,
    criticalAlerts: [
        "Emergency Rail Fracture repair 'JOB-EMERGENCY-01' successfully scheduled from 02:00 to 04:30 on FDB-PWL.",
        "Freight rake CONRAJ-01 regulation extended by 20 minutes to maintain passenger safety clearance.",
        "Zero delay imparted on premium Vande Bharat and Rajdhani express trains."
    ],
    impactSummary: "Emergency track block successfully accommodated in night corridor lull. Punctuality index maintained at 98.4%."
};
